name: habit_now
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_date_textbox: ^1.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  uuid: ^4.3.3
  wheel_chooser: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
